### ISSUE TITLE
Improve design (Effectie v2)

### ISSUE THREAD

**Issue by kevin-lee** [kevin-lee/effectie#300]
# Task
## Summary
Improve design (Effectie v2)

## Project Details
Version:

## Description
- [x] Make `Fx` `CanCatch` (#301)
- [x] Make `Fx` `CanHandleError` (#302)
- [x] Make `Fx` `CanRecover` (#303)
- [x] Core project should be effect library free (#304)
- [x] Sub-projects for Cats Effect and Monix (#305)
- [x] Remove `EffectConstructor` (#306)
- [x] Withdraw Scalaz Effect support (#308)
- [x] Remove `Xor` (#310)
- [x] Remove `Fx`, `FxCtor` and `CanCatch` `trait`s from `effectie-cats-effect`, `effectie-cats-effect3` and `effectie-monix`(#320)
- [x] Remove `CanHandleError` and `CanRecover` `trait`s from `effectie-cats-effect`, `effectie-cats-effect3` and `effectie-monix`(#322)
- [x] Test typeclasses for `Future` in the core project (#350)
- [x] Change `Effectful` to `fx` and move to `core` / also move possible `error` syntax to `core` (#352)
- [x] Rename the package of the `core` from `effectie` to `effectie.core` (#358)
- [x] Rename `Fx` and `FxCtor` in sub-projects to `fx` and `fxCtor` respectively (#361)
- [x] Redesign `ConsoleEffect` and `ConsoleEffectful` (#364)
- [x] Move `FromFuture` and `ToFuture` to core and leave only typeclass instances in the sub-projects (#367)
- [x] Uncapitalize typeclass instance names for Scala 2 (#371)
- [x] Move all sub-projects to modules (#373)
- [x] Upgrade `cats` to `2.7.0` (#377)
- [x] Add `effectie-cats` for cats specific code (#384)
- [x] Support Scala.js (#388)
- [x] Add `fromEither`, `fromOption` and `fromTry` to `FxCtor` and `Fx` (#393)
- [x] Clean up syntax (#421)
- [x] Use `effectie-cats-effect` common code for `effectie-monix` (#425)
- [x] Add `FxCtor.pureOrError(a)` and `Fx.pureOrError(a)` (#424)
- [x] syntax should have cats (`effectie.cats.syntax` and `effectie.syntax` => `effectie.syntax`) (#432)
- [x] Rename modules and packages (`effectie-cats` => `effectie-syntax`, `effectie-cats-effect` => `effectie-cats-effect2` and `effectie-monix` => `effectie-monix3`) (#430)
- [x] Reorganize instances - move to `effectie.instances` (#429)
- [x] Add `ReleasableResource` to automatically release resource after use (#443)
- [x] Update missing implicit instance messages for Scala 3 (#454)
- [x] Change `f` in `def catchNonFatal[A, B](fb: => F[B])(f: Throwable => A): F[Either[A, B]]` to `f: PartialFunction[Throwable, AA]` (#457)
- [x] Add `ResourceMaker` (#468)
- [x] Remove `implicit fxCtor: FxCtor[F]` param from the catch methods in `CanCatch` (#480)
- [x] Add `pureOfOption`, `pureOfSome`, `pureOfNone`, `pureOfRight` and `pureOfLeft` to `FxCtor` and `Fx` (#488)
