### ISSUE TITLE
Change pureEffect to effectOfPure

### ISSUE THREAD

**Issue by Kevin-Lee** [Kevin-Lee/effectie#33]
# Task
## Summary 
Change `pureEffect` in `effectOfPure`.

## Project Details
Version: `0.1.0`

## Description
Change `pureEffect` to `effectOfPure` as `pureEffect` may sound like creating a pure effect, yet it's actually creating an effect of pure value.
- [x] `EffectConstructor.pureEffect` => `EffectConstructor.effectOfPure`
- [x] `Effectful.pureEffect` => `Effectful.effectOfPure`
- [x] `effectie.scalaz.OptionTSupport.optionTPureEffect` => `effectie.scalaz.OptionTSupport.optionTEffectOfPure`
- [x] `effectie.scalaz.OptionTSupport.optionTLiftPureEffect` => `effectie.scalaz.OptionTSupport.optionTLiftEffectOfPure`
- [x] `effectie.scalaz.EitherTSupport.eitherTPureEffect` => `effectie.scalaz.EitherTSupport.eitherTEffectOfPure`
- [x] `effectie.scalaz.EitherTSupport.eitherTLiftPureEffect` => `effectie.scalaz.EitherTSupport.eitherTLiftEffectOfPure`
- [x] `effectie.cats.OptionTSupport.optionTPureEffect` => `effectie.cats.OptionTSupport.optionTEffectOfPure`
- [x] `effectie.cats.OptionTSupport.optionTLiftPureEffect` => `effectie.cats.OptionTSupport.optionTLiftEffectOfPure`
- [x] `effectie.cats.EitherTSupport.eitherTPureEffect` => `effectie.cats.EitherTSupport.eitherTEffectOfPure`
- [x] `effectie.cats.EitherTSupport.eitherTLiftPureEffect` => `effectie.cats.EitherTSupport.eitherTLiftEffectOfPure`
